### PR TITLE
Add client-side sign up form validation

### PR DESCRIPTION
**Pull request by xxczaki**
Note: Sorry for the "improve dockerfile" commit message - it comes from the recent commit and actually does not touch the mentioned file. The correct message should be "fix typo" 😄

### CODE REVIEW

**Review by v0idzz — CHANGES_REQUESTED** [review]
Please check `yarn.lock` in.

**Comment by xxczaki** [comment]
> Please check `yarn.lock` in.

~~I'm using npm, but sure, can do so ;)~~

Actually, I did not even check the error message of the failed action 😆

**Comment by xxczaki** [comment]
@v0idzz Had to fix some type errors as well, but it looks like everything works fine now.

**Review by v0idzz — APPROVED** [review]
LGTM

**Pull request merged**
