### PR TITLE
ShareSocial component

### PR DESCRIPTION
**Pull request by xxczaki**
> Still working from my fork, since I can't create & push to branches :cry:

Zrzut ekranu 2021-02-1 o 15 25 01

## To-do

- [x] Icons
- [x] Browser support issues
- [ ] URLs

## Questions

- Shall I use vector icons (`.svg` files) from Figma?
- Which browsers do we want to support? (This will help me choose/avoid specific features)
- What URL should I assign to each button? I already know about "Sztab" and social media ones (though we may want to share not only the URL of the page, but also a short message, like "Check out my myPolitics quiz results" etc).

cc @AdrianOrlow

### CODE REVIEW

**Comment by AdrianOrlow** [comment]
- We should use icons imported from `@fortawesome/free-solid-svg-icons` package, then add them to `library` (which bundles vectors into the build) imported from `@fortawesome/fontawesome-svg-core` and finally render via `FontAwesomeIcon` from `@fortawesome/react-fontawesome`. It's a standard process of injecting FontAwesome icons to React apps. Here's sample usage in our project https://github.com/mypolitics/mypolitics-3/blob/main/src/components/Survey/SingleSurveyPage/SurveyAnswers/SurveyAnswersView.tsx
- Most of the specific features can be polyfilled, so that's not a very big problem in most cases. However some css may not work properly in older (before 2020) versions of Safari, so we should check how the website performs on it. In addition, I will mention that of course IE may not be supported, only modern browsers (min. 85%-90% of the internet users).
- Links to social media:
 Sztab: https://www.facebook.com/groups/sztabmypolitics
 Polemika: https://www.facebook.com/groups/polemika

**Comment by xxczaki** [comment]
Current appearance:

Zrzut ekranu 2021-02-3 o 12 46 00

Besides adding icons and toast message on URL copy, I also updated our Babel configuration to support browsers, which have at least 2% global usage and aren't Internet Explorer. This will reduce our bundle size, improving performance.

Most modern JS features will, as you mentioned, be automatically polyfilled when needed. When it comes to CSS, I think we don't need to worry either - Next.js uses a [predefined PostCSS config, which includes some polyfills](https://nextjs.org/docs/advanced-features/customizing-postcss-config), including the one for the Flexbox `gap` property. It also works with styled-components.

The only things left are now:

- [ ] Create a Facebook & Twitter share URLs (which will include some custom text and a link from the `url` prop).
- [ ] Implement proper `box-shadow`s in the `ButtonUtils.ts` file (optional).
- [ ] i18n

cc @AdrianOrlow

**Review by AdrianOrlow — APPROVED** [review]
LGTM, good job :)

**Comment by xxczaki** [comment]
@AdrianOrlow Added proper share links for Facebook and Twitter, the "Social" section won't be visible when the language is not Polish and the "Share" section can now be translated :smile:

**Review by AdrianOrlow — APPROVED** [review]
Good job ;)

**Pull request merged**
